// TimeShift persistence schema (Drizzle) — the engine domain.
//
// This is the domain layer that extends scaffold-project's standard auth schema
// (sessions, users, audit_logs, invited_users, access_requests are generated by that
// scaffold and are not repeated here). It persists exactly what the engine holds:
// behaviour and structure, never content or secrets (the right of the Molo seam never
// enters this tree). Every jsonb column is typed against the engine's own types, so
// the database cannot drift from the resolver.
//
// NOTE: not yet wired into the build. Installing the Drizzle deps and adding this
// folder to a server tsconfig happens during the scaffold step, so the pure engine's
// existing typecheck and tests stay untouched until then.

import { pgTable, text, boolean, timestamp, jsonb, uuid, bigserial, integer, index } from "drizzle-orm/pg-core";
import type {
  Register,
  Scope,
  Kind,
  ResolutionBehaviour,
  Merge,
  SlotValue,
  Provenance,
  Interview,
  ValidatorSpec,
  EngineEventType,
} from "../src/index";

/** A region: an externally-imposed compliance origin (e.g. "ZA"). Broad scope. */
export const regions = pgTable("regions", {
  id: uuid("id").primaryKey().defaultRandom(),
  name: text("name").notNull(),
  /** Compliance version, stamped into resolution for determinism (L6). */
  version: text("version").notNull().default("v1"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

/** A tenant: a company. Its how-it-works lives at the tenant scope (P3). */
export const tenants = pgTable("tenants", {
  id: uuid("id").primaryKey().defaultRandom(),
  name: text("name").notNull(),
  regionId: uuid("region_id").references(() => regions.id),
  /** Tenant-engine version (SlotTree.versions.tenant). */
  version: text("version").notNull().default("v1"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

/** An agent: one staff member's assistant, owned by a tenant. */
export const agents = pgTable("agents", {
  id: uuid("id").primaryKey().defaultRandom(),
  tenantId: uuid("tenant_id").references(() => tenants.id).notNull(),
  name: text("name").notNull(),
  version: text("version").notNull().default("v1"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

/** Single-row config holding the universal root (timeshift) version. */
export const engineConfig = pgTable("engine_config", {
  id: integer("id").primaryKey().default(1),
  timeshiftVersion: text("timeshift_version").notNull().default("v1"),
});

/**
 * Slots: the atom of the engine, one row per authored slot. The owner columns place
 * the slot in the tree: timeshift slots set none, region slots set regionId, tenant
 * slots set tenantId, agent slots set agentId (and tenantId for isolation). The
 * resolver's guarantees are reproduced at the storage layer: tenant and agent slots
 * always carry tenantId so every assembly query can filter by it.
 */
export const slots = pgTable(
  "slots",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    scope: text("scope").$type<Scope>().notNull(),
    regionId: uuid("region_id").references(() => regions.id),
    tenantId: uuid("tenant_id").references(() => tenants.id),
    agentId: uuid("agent_id").references(() => agents.id),
    key: text("key").notNull(),
    register: text("register").$type<Register>().notNull(),
    kind: text("kind").$type<Kind>().notNull(),
    behaviour: text("behaviour").$type<ResolutionBehaviour>().notNull(),
    /** List slots only (L8). */
    merge: text("merge").$type<Merge>(),
    /** Constraint slots only. */
    steer: boolean("steer"),
    /** Constraint slots only: the declarative check from the closed vocabulary. */
    check: jsonb("check").$type<ValidatorSpec>(),
    interview: jsonb("interview").$type<Interview>(),
    defaultValue: jsonb("default_value").$type<SlotValue>().notNull(),
    provenance: jsonb("provenance").$type<Provenance>().notNull(),
    answerVersionStamp: text("answer_version_stamp").notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (t) => ({
    tenantIdx: index("slots_tenant_idx").on(t.tenantId),
    agentIdx: index("slots_agent_idx").on(t.agentId),
    regionIdx: index("slots_region_idx").on(t.regionId),
    scopeIdx: index("slots_scope_idx").on(t.scope),
  }),
);

/** Skills: stable behaviour bodies inherited through the tree (Section 6). Same owner
 *  columns as slots; the body is loaded lazily at render time, not stored differently. */
export const skills = pgTable(
  "skills",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    scope: text("scope").$type<Scope>().notNull(),
    regionId: uuid("region_id").references(() => regions.id),
    tenantId: uuid("tenant_id").references(() => tenants.id),
    agentId: uuid("agent_id").references(() => agents.id),
    name: text("name").notNull(),
    description: text("description").notNull(),
    body: text("body").notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (t) => ({
    tenantIdx: index("skills_tenant_idx").on(t.tenantId),
    agentIdx: index("skills_agent_idx").on(t.agentId),
  }),
);

/**
 * The provenance / event log: the visibility substrate (Section 9), as a ledger.
 *
 * Append-only by the ledger rule: rows are inserted, never updated or deleted. The
 * storage layer exposes only insert and select; a hardening step later revokes UPDATE
 * and DELETE at the database role so the rule is enforced below the application too.
 * `seq` is a bigserial, giving the same monotonic ordering as the in-memory log.
 */
export const engineEvents = pgTable(
  "engine_events",
  {
    seq: bigserial("seq", { mode: "number" }).primaryKey(),
    type: text("type").$type<EngineEventType>().notNull(),
    tenantId: uuid("tenant_id").references(() => tenants.id),
    at: timestamp("at").defaultNow().notNull(),
    detail: jsonb("detail").$type<Record<string, unknown>>().notNull().default({}),
    provenance: jsonb("provenance").$type<Provenance>(),
  },
  (t) => ({
    tenantIdx: index("engine_events_tenant_idx").on(t.tenantId),
    typeIdx: index("engine_events_type_idx").on(t.type),
  }),
);
